#!/usr/bin/env bash

# Fetch display output information and format it
get_display_info() {
  swaymsg -t get_outputs | jq -r '
        .[] | {
            name,
            mode_width: .current_mode.width,
            mode_height: .current_mode.height,
            mode_refresh: ( .current_mode.refresh / 1000 ),
            pos_x: .rect.x,
            pos_y: .rect.y,
            scale,
            transform
        }
        | "output \"\(.name)\" position \(.pos_x),\(.pos_y) mode \(.mode_width)x\(.mode_height)@\(.mode_refresh) scale \(.scale) transform \(.transform)"
    '
}

# Main script
display_info=$(get_display_info)
echo "$display_info"

# e.g.
# output "DP-1" position 0,0 mode 1920x1200@59.885 scale 1.0 transform normal
# output "eDP-1" position 1920,0 mode 1920x1080@144 scale 1.0 transform normal
