unbind C-b
set -g prefix C-space

set  -g base-index      1
setw -g pane-base-index 1

bind-key x kill-pane

set  -g default-terminal   "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features  ",xterm-256color:clipboard"

# Copy highlighted content once drag finishes
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @catppuccin_flavor "latte"

run ~/.tmux/plugins/tpm/tpm
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-left ""
set -g status-right "#[fg=#{@thm_crust},bg=#{@thm_teal}] #S #[fg=#{@thm_crust},bg=#{@thm_mauve}] %k:%M %d-%m-%y "
set -g status-right-length 100

set -g window-status-format "#[fg=#{@thm_crust},bg=#{@thm_text}] #I #[default] #[fg=#{@thm_text},bold]#{b:pane_current_path}"
set -g window-status-current-format "#[fg=#{@thm_crust},bg=#{@thm_flamingo}] #I #[default] #[fg=#{@thm_rosewater},bold]#{b:pane_current_path}"
