shell /usr/bin/zsh

font_family JetBrainsMono NF
font_size   16.0

# font size management 
map ctrl+shift+backspace change_font_size all 0

# colours
# include ${KITTY_THEME}.conf
include duskfox.conf
